[appendix]
[[Appendix-contributors]]
== Contributors
1. Roger Lopez - content review, technical content review (RHEL-OSP)
2. Babak Mozaffari - technical content review (JBOSS EAP)
3. Dan Sneddon - technical content review (Network isolation)
4. Keith Schincke - technical content review (Ceph)
5. Andrew Beekhoff - technical content review (HA)
6. Steven Reichard -- content review, technical content review
   (RHEL-OSP)
7. Scott Lewis -- content review, messaging
8. Vinny Valdez -- content review, technical content review (RHEL-OSP)

[appendix]
[[Appendix-references]]
== References

=== Ceph References
. http://ceph.com/docs/master/rados/operations/placement-groups/[Ceph
  Placement Groups]
. https://wiki.ceph.com/Guides/How_To/Benchmark_Ceph_Cluster_Performance[Benchmark
Ceph Cluster Performance]
. https://access.redhat.com/articles/1321163[2015 - RHEL OSP 5: Cinder Volume Performance on Inktank Ceph
Enterprise 1.2.2]
. https://access.redhat.com/documentation/en/red-hat-ceph-storage/version-1.3/red-hat-ceph-storage-13-red-hat-ceph-architecture/red-hat-ceph-architecture[
Red Hat Ceph Architecture Guide]
. https://access.redhat.com/articles/1370143[2015 - Deploying Highly
  Available Red Hat Enterprise Linux OpenStack Platform 6 with Ceph
  Storage]

=== eDeploy and AHC References
. https://github.com/redhat-cip/edeploy/blob/master/docs/eDeployUserGuide.rst[eDeploy
  User's Guide]
. https://github.com/redhat-cip/edeploy/blob/master/docs/AHC.rst[
Automatic Health Check (AHC) - User Guide]

=== Heat References
. http://docs.openstack.org/developer/heat/template_guide/hot_spec.html[Heat
  Orchestration Template (HOT) specification]
. http://hardysteven.blogspot.com/2015/04/debugging-tripleo-heat-templates.html[Debugging
TripleO Heat templates]

=== JBOSS EAP References
. https://access.redhat.com/solutions/1320133[How can I execute the
  JBoss EAP 6 using Systemctl?]
. https://access.redhat.com/articles/1452603[2015 - Microservice
  Architecture: Building microservices with JBoss EAP 6]

=== Red Hat OpenStack Platform References
. https://access.redhat.com/articles/1507893[2015 - Guidelines and
Considerations for Performance and Scaling your Red Hat Openstack 6
Cloud]
. https://access.redhat.com/articles/1273073[Performance Tuning for
RabbitMQ in Red Hat Enterprise Linux OpenStack Platform]
. https://access.redhat.com/articles/1432053[Performance tuning the
backend database for Red Hat Enterprise Linux OpenStack Platform]
. https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html-single/Virtualization_Tuning_and_Optimization_Guide/index.html[Red Hat Enterprise Linux 6 Virtualization Tuning and Optimization Guide]
. http://people.redhat.com/berrange/kvm-forum-2014/kvm-forum-2014-openstack-perf.pdf[OpenStack
Performance Optimization]
. https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/7/html/Director_Installation_and_Usage/[Red Hat Enterprise Linux OpenStack Platform 7 Director Installation and Usage]
. https://access.redhat.com/articles/973163[Certified Guest Operating
Systems in Red Hat Enterprise Linux OpenStack Platform and Red Hat
Enterprise Virtualization]
https://access.redhat.com/articles/1436373[Deployment Limits for Red
Hat OpenStack Platform]
. https://access.redhat.com/documentation/en-US/Red_Hat_Satellite/6.0/pdf/Provisioning_Guide/Red_Hat_Satellite-6.0-Provisioning_Guide-en-US.pdf[The
Red Hat Satellite 6.0 Provisioning Guide]
. https://access.redhat.com/articles/1462803[Understanding RHEL
  OpenStack Platform High Availability (RHEL OSP7 and Director)]

[appendix]
[[Appendix-hardware-specifications]]
== Hardware specifications

.Hardware specifications
[options="header"]
|====
|Count|Model|Description
|8|Dell PowerEdge M520|2x Intel Xeon CPU E5-2450 0 @ 2.10GHz, Broadcom 5720 1Gb Dual Port LOMs, Broadcom 57810S-k
Dual Port 10Gb NIC, 6x DDR3 8192 MB @1333 MHZ DIMMs, 2 x 146GB SAS
internal disk drives
|4|Dell PowerEdge R510|2x Intel(R) Xeon(R) CPU X5650 @ 2.67 GHz (6
core), 2 x Broadcom NetXtreme II BCM5709S Gb Ethernet, 2x  Emulex
Corporation OneConnect 10Gb NIC, 6 x DDR3 8192 MB @1333 MHZ DIMMs, 12x
146GB SAS internal disk drives
|1|Dell PowerEdge R720xd|2x Intel(R) Xeon(R) CPU X5650 @ 2.67 GHz (6
core), 2 x Broadcom NetXtreme II BCM5709S Gb Ethernet, 2x  Emulex
Corporation OneConnect 10Gb NIC, 6 x DDR3 8192 MB @1333 MHZ DIMMs, 12x
146GB SAS internal disk drives
|====

[appendix]
[[Appendix-required-channels]]
== Required channels
{ospver} is available via the {cdn} or {rhss}.

.Required channels
[options="header"]
|====
|Name|Description
|rhel-7-server-extras-rpms|Red Hat Enterprise Linux 7 Server - Extras
|rhel-7-server-openstack-7.0-director-rpms|Red Hat OpenStack 7.0 director for RHEL 7 (RPMs)
|rhel-7-server-openstack-7.0-rpms|Red Hat OpenStack 7.0 for RHEL 7 (RPMs)
|rhel-7-server-optional-rpms|Red Hat Enterprise Linux 7 Server - Optional (RPMs)
|rhel-7-server-rpms|Red Hat Enterprise Linux 7 Server (RPMs)
|====

NOTE: This reference architecture uses a local satellite server for
deployments and updates.

[appendix]
[[Appendix-undercloud-SSL]]
== Deploying undercloud with SSL

This appendix describes steps for deploying the undercloud with SSL
support.

NOTE: The
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/7/html/Director_Installation_and_Usage/sect-Configuring_the_Director.html[product
documentation] includes additional information for installing the
undercloud with SSL support.


1. Generate a private key file.
+
[subs=+quotes]
----
$ *openssl genrsa -out privkey.pem 2048*
Generating RSA private key, 2048 bit long modulus
.....................................................................+++
.........+++
e is 65537 (0x10001)
----

2. Create the distinguished identifier for the certificate.
+
NOTE: Replace this example with appropriate environment-specific answers.
+
[subs=+quotes]
----
$ *openssl req -new -x509 -key privkey.pem -out cacert.pem -days 365*
You are about to be asked to enter information that will be
incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or
a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
\-----
Country Name (2 letter code) [XX]:*US*
State or Province Name (full name) []:*Texas*
Locality Name (eg, city) [Default City]:*Austin*
Organization Name (eg, company) [Default Company Ltd]:*Red Hat*
Organizational Unit Name (eg, section) []:*Systems Engineering*
Common Name (eg, your name or your server's hostname) []:*192.0.2.2*
Email Address []:*jliberma@redhat.com*
----

3. Write the certificate and key to _undercloud.pem_.
+
[subs=+quotes]
----
$ *cat cacert.pem privkey.pem > undercloud.pem*
----

4. Copy the combined SSL key to _/etc/pki/instal-cert/_.
+
[subs=+quotes]
----
$ *sudo mkdir /etc/pki/instack-certs*
$ *sudo cp ~/undercloud.pem /etc/pki/instack-certs/.*
----

5. Set the SELinux context on the key certificate directory and files.
+
[subs=+quotes]
----
$ **sudo semanage fcontext -a -t etc_t "/etc/pki/instack-certs(/.\*)?"**
----

6. Run *restorecon* to enforce the new SELinux contexts.
+
[subs=+quotes]
----
$ *sudo restorecon -R /etc/pki/instack-certs*
----

7. Modify the undercloud.conf from the previous example to include:
.. An undercloud public VIP
.. An undercloud private VIP
.. The location for the undercloud service certificate.
+
[subs=+quotes]
----
$ *head undercloud.conf*
[DEFAULT]

image_path = .
local_ip = 192.0.2.1/24
undercloud_public_vip = 192.0.2.2
undercloud_admin_vip = 192.0.2.3
undercloud_service_certificate = /etc/pki/instack-certs/undercloud.pem
local_interface = eno4
masquerade_network = 192.0.2.0/24
dhcp_start = 192.0.2.5
----

8. Install the undercloud with SSL support.
+
[subs=+quotes]
----
$ *openstack undercloud install*
...
#############################################################################
instack-install-undercloud complete.

The file containing this installation's passwords is at
/home/stack/undercloud-passwords.conf.

There is also a stackrc file at /home/stack/stackrc.

These files are needed to interact with the OpenStack services, and
should be
secured.

#############################################################################
----
9. Source _stackrc_ and verify the OpenStack services have separate
  internal and public endpoint URLs.
+
[subs=+quotes]
----
$ *source ~stackrc*
$ *openstack endpoint show glance*
    +--------------+----------------------------------+
    | Field        | Value                            |
    +--------------+----------------------------------+
    | adminurl     | http://192.0.2.1:9292/           |
    | enabled      | True                             |
    | id           | 6f715600451f433f98e38b72a5b70606 |
    | internalurl  | http://192.0.2.1:9292/           |
    | publicurl    | https://192.0.2.2:13292/         |
    | region       | regionOne                        |
    | service_id   | 8553ca00fa2c4aa98b1d60aa53df3f89 |
    | service_name | glance                           |
    | service_type | image                            |
    +--------------+----------------------------------+
----

[appendix]
[[Appendix-undercloud-servce-list]]
== Undercloud Service List

[subs=+quotes]
----
neutron-dhcp-agent
neutron-openvswitch-agent
neutron-server
openstack-ceilometer-alarm-evaluator
openstack-ceilometer-alarm-notifier
openstack-ceilometer-api
openstack-ceilometer-central
openstack-ceilometer-collector
openstack-ceilometer-notification
openstack-glance-api
openstack-glance-registry
openstack-heat-api-cfn
openstack-heat-api-cloudwatch
openstack-heat-api
openstack-heat-engine
openstack-ironic-api
openstack-ironic-conductor
openstack-ironic-discoverd-dnsmasq
openstack-ironic-discoverd
openstack-keystone
openstack-nova-api
openstack-nova-compute
openstack-nova-conductor
openstack-nova-consoleauth
openstack-nova-scheduler
openstack-swift-account-auditor
openstack-swift-account-reaper
openstack-swift-account-replicator
openstack-swift-account
openstack-swift-container-auditor
openstack-swift-container-replicator
openstack-swift-container-updater
openstack-swift-container
openstack-swift-object-auditor
openstack-swift-object-replicator
openstack-swift-object-updater
openstack-swift-object
openstack-swift-proxy
openstack-tuskar-api
----

[appendix]
[[Appendix-overcloud-servce-list]]
== Overcloud Service List

[subs=+quotes]
----
Cluster name: tripleo_cluster
Last updated: Tue Sep  8 12:41:33 2015
Last change: Tue Sep  8 11:47:03 2015
Stack: corosync
Current DC: overcloud-controller-2 (3) - partition with quorum
Version: 1.1.12-a14efad
3 Nodes configured
112 Resources configured

Online: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]

Full list of resources:

 ip-192.0.2.6   (ocf::heartbeat:IPaddr2):       Started overcloud-controller-0
 Clone Set: haproxy-clone [haproxy]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 ip-172.16.1.11 (ocf::heartbeat:IPaddr2):       Started overcloud-controller-1
 ip-10.19.137.121       (ocf::heartbeat:IPaddr2):       Started overcloud-controller-2
 ip-172.16.2.10 (ocf::heartbeat:IPaddr2):       Started overcloud-controller-0
 ip-172.16.1.10 (ocf::heartbeat:IPaddr2):       Started overcloud-controller-1
 Master/Slave Set: galera-master [galera]
     Masters: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 ip-172.16.3.10 (ocf::heartbeat:IPaddr2):       Started overcloud-controller-2
 Master/Slave Set: redis-master [redis]
     Masters: [ overcloud-controller-2 ]
     Slaves: [ overcloud-controller-0 overcloud-controller-1 ]
 Clone Set: mongod-clone [mongod]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: rabbitmq-clone [rabbitmq]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: memcached-clone [memcached]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-nova-scheduler-clone [openstack-nova-scheduler]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: neutron-l3-agent-clone [neutron-l3-agent]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-ceilometer-alarm-notifier-clone [openstack-ceilometer-alarm-notifier]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-heat-engine-clone [openstack-heat-engine]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-ceilometer-api-clone [openstack-ceilometer-api]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: neutron-metadata-agent-clone [neutron-metadata-agent]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: neutron-ovs-cleanup-clone [neutron-ovs-cleanup]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: neutron-netns-cleanup-clone [neutron-netns-cleanup]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-heat-api-clone [openstack-heat-api]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-cinder-scheduler-clone [openstack-cinder-scheduler]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-nova-api-clone [openstack-nova-api]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-heat-api-cloudwatch-clone [openstack-heat-api-cloudwatch]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-ceilometer-collector-clone [openstack-ceilometer-collector]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-keystone-clone [openstack-keystone]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-nova-consoleauth-clone [openstack-nova-consoleauth]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-glance-registry-clone [openstack-glance-registry]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-ceilometer-notification-clone [openstack-ceilometer-notification]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-cinder-api-clone [openstack-cinder-api]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: neutron-dhcp-agent-clone [neutron-dhcp-agent]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-glance-api-clone [openstack-glance-api]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: neutron-openvswitch-agent-clone [neutron-openvswitch-agent]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-nova-novncproxy-clone [openstack-nova-novncproxy]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: delay-clone [delay]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: neutron-server-clone [neutron-server]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: httpd-clone [httpd]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-ceilometer-central-clone [openstack-ceilometer-central]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-ceilometer-alarm-evaluator-clone [openstack-ceilometer-alarm-evaluator]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 Clone Set: openstack-heat-api-cfn-clone [openstack-heat-api-cfn]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]
 openstack-cinder-volume        (systemd:openstack-cinder-volume):      Started overcloud-controller-2
 Clone Set: openstack-nova-conductor-clone [openstack-nova-conductor]
     Started: [ overcloud-controller-0 overcloud-controller-1 overcloud-controller-2 ]

PCSD Status:
  overcloud-controller-0: Online
  overcloud-controller-1: Online
  overcloud-controller-2: Online

Daemon Status:
  corosync: active/enabled
  pacemaker: active/enabled
  pcsd: active/enabled
----

[appendix]
[[Appendix-controller_fencing_script]]
== Example fencing Script
This script was used by the Red Hat Systems Engineering team to
configure and test `Pacemaker` fencing. The script is not tested nor
suitable for production use. It is included as a reference for
manually configuring fencing or as an example for scripted
configuration.

[source%autofit, shell]
----
#!/bin/bash

source ~/stackrc
env | grep OS_
SSH_CMD="ssh -l heat-admin"

function usage {
        echo "USAGE: $0 [enable|test]"
        exit 1
}

function enable_stonith {
        # for all controller nodes
        for i in $(nova list | awk ' /controller/ { print $12 } ' | cut -f2 -d=)
        do
                echo $i
                # create the fence device
                $SSH_CMD $i 'sudo pcs stonith create $(hostname -s)-ipmi fence_ipmilan pcmk_host_list=$(hostname -s) ipaddr=$(sudo ipmitool lan print 1 | awk " /IP Address  / { print \$4 } ") login=root passwd=PASSWORD lanplus=1 cipher=1 op monitor interval=60sr'
                # avoid fencing yourself
                $SSH_CMD $i 'sudo pcs constraint location $(hostname -s)-ipmi avoids $(hostname -s)'
        done

        # enable STONITH devices from any controller
        $SSH_CMD $i 'sudo pcs property set stonith-enabled=true'
        $SSH_CMD $i 'sudo pcs property show'
}

function test_fence {

        for i in $(nova list | awk ' /controller/ { print $12 } ' | cut -f2 -d= | head -n 1)
        do
                # get REDIS_IP
                REDIS_IP=$($SSH_CMD $i 'sudo grep -ri redis_vip /etc/puppet/hieradata/' | awk '/vip_data.yaml/ { print $2 } ')
        done
        # for all controller nodes
        for i in $(nova list | awk ' /controller/ { print $12 } ' | cut -f2 -d=)
        do
                if $SSH_CMD $i "sudo ip a" | grep -q $REDIS_IP
                then
                        FENCE_DEVICE=$($SSH_CMD $i 'sudo pcs stonith show $(hostname -s)-ipmi' | awk ' /Attributes/ { print $2 } ' | cut -f2 -d=)
                        IUUID=$(nova list | awk " /$i/ { print \$2 } ")
                        UUID=$(ironic node-list | awk " /$IUUID/ { print \$2 } ")
                else
                        FENCER=$i
                fi
        done 2>/dev/null

        echo "REDIS_IP $REDIS_IP"
        echo "FENCER $FENCER"
        echo "FENCE_DEVICE $FENCE_DEVICE"
        echo "UUID $UUID"
        echo "IUUID $IUUID"

        # stonith REDIS_IP owner
        $SSH_CMD $FENCER sudo pcs stonith fence $FENCE_DEVICE

        sleep 30

        # fence REDIS_IP owner to keep ironic from powering it on
        sudo ironic node-set-power-state $UUID off

        sleep 60

        # check REDIS_IP failover
        $SSH_CMD $FENCER sudo pcs status | grep $REDIS_IP
}

if [ "$1" == "test" ]
then
        test_fence
elif [ "$1" == "enable" ]
then
        enable_stonith
else
        usage
fi
----

[appendix]
[[Appendix-nic-configuration-files]]
== NIC Confguration Files
This appendix includes the full text of the network isolation
environment files used in this use case.

NOTE: The _swift-storage.yaml_ and _cinder-storage.yaml_ are not shown
because they were not used.

=== network-environment.yaml
[source%autofit, shell]
----
resource_registry:
  OS::TripleO::BlockStorage::Net::SoftwareConfig: /home/stack/nic-configs/cinder-storage.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: /home/stack/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: /home/stack/nic-configs/controller.yaml
  OS::TripleO::ObjectStorage::Net::SoftwareConfig: /home/stack/nic-configs/swift-storage.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig: /home/stack/nic-configs/ceph-storage.yaml

parameter_defaults:
  ControlPlaneSubnetCidr: "24"
  ControlPlaneDefaultRoute: 192.0.2.1
  EC2MetadataIp: 192.0.2.1
  NeutronExternalNetworkBridge: "br-ex"
  InternalApiNetCidr: 172.16.1.0/24
  StorageNetCidr: 172.16.2.0/24
  StorageMgmtNetCidr: 172.16.3.0/24
  TenantNetCidr: 172.16.4.0/24
  ExternalNetCidr: 10.19.136.0/21
  InternalApiAllocationPools: [{'start': '172.16.1.10', 'end': '172.16.1.100'}]
  StorageAllocationPools: [{'start': '172.16.2.10', 'end': '172.16.2.200'}]
  StorageMgmtAllocationPools: [{'start': '172.16.3.10', 'end': '172.16.3.200'}]
  TenantAllocationPools: [{'start': '172.16.4.10', 'end': '172.16.4.200'}]
  ExternalAllocationPools: [{'start': '10.19.137.121', 'end': '10.19.137.151'}]
  InternalApiNetworkVlanID: 4041
  StorageNetworkVlanID: 4042
  StorageMgmtNetworkVlanID: 4043
  TenantNetworkVlanID: 4044
  ExternalNetworkVlanID: 168
  ExternalInterfaceDefaultRoute: "10.19.143.254"
  BondInterfaceOvsOptions:
      "bond_mode=balance-tcp lacp=active other-config:lacp-fallback-ab=true"
----
=== controller.yaml
[source%autofit, shell]
----
heat_template_version: 2015-04-30

description: >
  Software Config to drive os-net-config to configure VLANs for the
  controller role.

parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ControlPlaneSubnetCidr:
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  EC2MetadataIp:
    description: The IP address of the EC2 metadata server.
    type:  string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  ExternalNetworkVlanID:
    default: 168
    description: Vlan ID for the external network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 4041
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 4042
    description: Vlan ID for the storage network traffic.
    type: number
  StorageMgmtNetworkVlanID:
    default: 4043
    description: Vlan ID for the storage mgmt network traffic.
    type: number
  TenantNetworkVlanID:
    default: 4044
    description: Vlan ID for the tenant network traffic.
    type: number
  ExternalInterfaceDefaultRoute:
    default: '10.19.143.254'
    description: Default route for the external network.
    type: string

resources:
  OsNetConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        os_net_config:
          network_config:
            -
              type: ovs_bridge
              name: br-ex
              use_dhcp: false
              addresses:
              -
                ip_netmask: {get_param: ExternalIpSubnet}
              routes:
                -
                  ip_netmask: 0.0.0.0/0
                  next_hop: {get_param: ExternalInterfaceDefaultRoute}
              members:
                -
                  type: interface
                  name: nic1
                  primary: true
            -
              type: ovs_bridge
              name: br-nic3
              use_dhcp: false
              addresses:
                -
                  ip_netmask: {get_param: TenantIpSubnet}
              members:
                -
                  type: interface
                  name: nic3
                  primary: true
                -
                  type: vlan
                  vlan_id: {get_param: StorageMgmtNetworkVlanID}
                  addresses:
                  -
                    ip_netmask: {get_param: StorageMgmtIpSubnet}
            -
              type: ovs_bridge
              name: br-nic4
              use_dhcp: false
              addresses:
                -
                  ip_netmask: {get_param: StorageIpSubnet}
              members:
                -
                  type: interface
                  name: nic4
                  primary: true
                -
                  type: vlan
                  vlan_id: {get_param: InternalApiNetworkVlanID}
                  addresses:
                  -
                    ip_netmask: {get_param: InternalApiIpSubnet}

outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value: {get_resource: OsNetConfigImpl}
----
=== compute.yaml
[source%autofit, shell]
----
heat_template_version: 2015-04-30

description: >
  Software Config to drive os-net-config with 2 bonded nics on a bridge
  with a VLANs attached for the compute role.

parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ControlPlaneSubnetCidr:
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  EC2MetadataIp:
    description: The IP address of the EC2 metadata server.
    type:  string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  InternalApiNetworkVlanID:
    default: 4041
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 4042
    description: Vlan ID for the storage network traffic.
    type: number
  TenantNetworkVlanID:
    default: 4044
    description: Vlan ID for the tenant network traffic.
    type: number

resources:
  OsNetConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        os_net_config:
          network_config:
            -
              type: interface
              name: nic1
              use_dhcp: false
            -
              type: ovs_bridge
              name: br-nic3
              use_dhcp: false
              addresses:
                -
                  ip_netmask: {get_param: TenantIpSubnet}
              members:
                -
                  type: interface
                  name: nic3
                  primary: true
            -
              type: ovs_bridge
              name: br-nic4
              use_dhcp: false
              addresses:
                -
                  ip_netmask: {get_param: StorageIpSubnet}
              members:
                -
                  type: interface
                  name: nic4
                  primary: true
                -
                  type: vlan
                  vlan_id: {get_param: InternalApiNetworkVlanID}
                  addresses:
                  -
                    ip_netmask: {get_param: InternalApiIpSubnet}


outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value: {get_resource: OsNetConfigImpl}
----
=== ceph-storage.yaml
[source%autofit, shell]
----
heat_template_version: 2015-04-30

description: >
  Software Config to drive os-net-config to configure VLANs for the
  ceph-storage role.

parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ControlPlaneSubnetCidr:
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  EC2MetadataIp:
    description: The IP address of the EC2 metadata server.
    type:  string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  ExternalNetworkVlanID:
    default: 168
    description: Vlan ID for the external network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 4041
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 4042
    description: Vlan ID for the storage network traffic.
    type: number
  StorageMgmtNetworkVlanID:
    default: 4043
    description: Vlan ID for the storage mgmt network traffic.
    type: number
  TenantNetworkVlanID:
    default: 4044
    description: Vlan ID for the tenant network traffic.
    type: number
  ExternalInterfaceDefaultRoute:
    default: '10.19.143.254'
    description: Default route for the external network.
    type: string

resources:
  OsNetConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        os_net_config:
          network_config:
            -
              type: interface
              name: nic1
              use_dhcp: false
            -
              type: ovs_bridge
              name: br-nic3
              use_dhcp: false
              members:
                -
                  type: interface
                  name: nic3
                -
                  type: vlan
                  vlan_id: {get_param: StorageMgmtNetworkVlanID}
                  addresses:
                    -
                      ip_netmask: {get_param: StorageMgmtIpSubnet}
            -
              type: interface
              name: nic4
              addresses:
                -
                  ip_netmask: {get_param: StorageIpSubnet}

outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value: {get_resource: OsNetConfigImpl}
heat_template_version: 2015-04-3heat_template_version: 2015-04-30

description: >
  Software Config to drive os-net-config to configure VLANs for the
  ceph-storage role.

parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ControlPlaneSubnetCidr:
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  EC2MetadataIp:
    description: The IP address of the EC2 metadata server.
    type:  string
  ExternalIpSubnet:
    default: ''
    description: IP address/subnet on the external network
    type: string
  InternalApiIpSubnet:
    default: ''
    description: IP address/subnet on the internal API network
    type: string
  StorageIpSubnet:
    default: ''
    description: IP address/subnet on the storage network
    type: string
  StorageMgmtIpSubnet:
    default: ''
    description: IP address/subnet on the storage mgmt network
    type: string
  TenantIpSubnet:
    default: ''
    description: IP address/subnet on the tenant network
    type: string
  ExternalNetworkVlanID:
    default: 168
    description: Vlan ID for the external network traffic.
    type: number
  InternalApiNetworkVlanID:
    default: 4041
    description: Vlan ID for the internal_api network traffic.
    type: number
  StorageNetworkVlanID:
    default: 4042
    description: Vlan ID for the storage network traffic.
    type: number
  StorageMgmtNetworkVlanID:
    default: 4043
    description: Vlan ID for the storage mgmt network traffic.
    type: number
  TenantNetworkVlanID:
    default: 4044
    description: Vlan ID for the tenant network traffic.
    type: number
  ExternalInterfaceDefaultRoute:
    default: '10.19.143.254'
    description: Default route for the external network.
    type: string

resources:
  OsNetConfigImpl:
    type: OS::Heat::StructuredConfig
    properties:
      group: os-apply-config
      config:
        os_net_config:
          network_config:
            -
              type: interface
              name: nic1
              use_dhcp: false
            -
              type: ovs_bridge
              name: br-nic3
              use_dhcp: false
              members:
                -
                  type: interface
                  name: nic3
                -
                  type: vlan
                  vlan_id: {get_param: StorageMgmtNetworkVlanID}
                  addresses:
                    -
                      ip_netmask: {get_param: StorageMgmtIpSubnet}
            -
              type: interface
              name: nic4
              addresses:
                -
                  ip_netmask: {get_param: StorageIpSubnet}

outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value: {get_resource: OsNetConfigImpl}0
----

[appendix]
[[Appendix-revision-history]]
== Revision History

.Revision History
[cols="a,a,a"]
|====
|Revision 2.0|Monday, November 9, 2015|Jacob Liberman
3+|
- Updates for Y1 release

|Revision 1.0|Wednesday, September 9, 2015|Jacob Liberman
3+|
- Initial publication based on 0-day release and reviews +
- Ported to asciidoc template
|====


// vim: set syntax=asciidoc:
