[appendix]
== Contributors
1. Roger Lopez - Content review, technical content review (OSP)
2. Babak Mozaffari - technical content review (JBOSS EAP)
3. Dan Sneddon - technical content review (Network isolation)
4. Keith Schincke - technical content review (Ceph)
5. Andrew Beekhoff - technical content review (HA)

[appendix]
== References

=== Ceph
. http://ceph.com/docs/master/rados/operations/placement-groups/[Ceph
  Placement Groups]
. https://wiki.ceph.com/Guides/How_To/Benchmark_Ceph_Cluster_Performance[Benchmark
Ceph Cluster Performance]
. https://access.redhat.com/articles/1321163[2015 - RHEL OSP 5: Cinder Volume Performance on Inktank Ceph
Enterprise 1.2.2]
. https://access.redhat.com/documentation/en/red-hat-ceph-storage/version-1.3/red-hat-ceph-storage-13-red-hat-ceph-architecture/red-hat-ceph-architecture[
Red Hat Ceph Architecture Guide]
. https://access.redhat.com/articles/1370143[2015 - Deploying Highly
  Available Red Hat Enterprise Linux OpenStack Platform 6 with Ceph
  Storage]

=== eDeploy and AHC
. https://github.com/redhat-cip/edeploy/blob/master/docs/eDeployUserGuide.rst[eDeploy
  User's Guide]
. https://github.com/redhat-cip/edeploy/blob/master/docs/AHC.rst[
Automatic Health Check (AHC) - User Guide]

=== Heat
. http://docs.openstack.org/developer/heat/template_guide/hot_spec.html[Heat
  Orchestration Template (HOT) specification]
. http://docs.openstack.org/developer/heat/template_guide/[Heat
  Orchestration Template (HOT) Guide]
. http://hardysteven.blogspot.com/2015/04/debugging-tripleo-heat-templates.html[Debugging
TripleO Heat templates]

=== JBOSS EAP
. https://access.redhat.com/solutions/1320133[How can I execute the
  JBoss EAP 6 using Systemctl?]
. https://access.redhat.com/articles/1452603[2015 - Microservice
  Architecture: Building microservices with JBoss EAP 6]

=== Red Hat OpenStack Platform
. https://access.redhat.com/articles/1507893[2015 - Guidelines and
Considerations for Performance and Scaling your Red Hat Openstack 6
Cloud]
. https://access.redhat.com/articles/1273073[Performance Tuning for
RabbitMQ in Red Hat Enterprise Linux OpenStack Platform]
. https://access.redhat.com/articles/1432053[Performance tuning the
backend database for Red Hat Enterprise Linux OpenStack Platform]
. https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html-single/Virtualization_Tuning_and_Optimization_Guide/index.html[Red Hat Enterprise Linux 6 Virtualization Tuning and Optimization Guide]
. http://people.redhat.com/berrange/kvm-forum-2014/kvm-forum-2014-openstack-perf.pdf[OpenStack
Performance Optimization]
. https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/7/html/Director_Installation_and_Usage/[Red Hat Enterprise Linux OpenStack Platform 7 Director Installation and Usage]
. https://access.redhat.com/articles/973163[Certified Guest Operating
Systems in Red Hat Enterprise Linux OpenStack Platform and Red Hat
Enterprise Virtualization]
https://access.redhat.com/articles/1436373[Deployment Limits for Red
Hat OpenStack Platform]
. https://access.redhat.com/documentation/en-US/Red_Hat_Satellite/6.0/pdf/Provisioning_Guide/Red_Hat_Satellite-6.0-Provisioning_Guide-en-US.pdf[The
Red Hat Satellite 6.0 Provisioning Guide]

[appendix]
[[hardware-specifications]]
== Hardware specifications

.Hardware specifications
[options="header,footer"]
|====
|Count|Model|Description
|8|Dell PowerEdge M520|2x Intel Xeon CPU E5-2450 0 @ 2.10GHz, Broadcom 5720 1Gb Dual Port LOMs, Broadcom 57810S-k
Dual Port 10Gb NIC, 6x DDR3 8192 MB @1333 MHZ DIMMs, 2 x 146GB SAS
internal disk drives
|4|Dell PowerEdge R520|2x Intel(R) Xeon(R) CPU X5650 @ 2.67 GHz (6
core), 2 x Broadcom NetXtreme II BCM5709S Gb Ethernet, 2x  Emulex
Corporation OneConnect 10Gb NIC, 6 x DDR3 8192 MB @1333 MHZ DIMMs, 12x
146GB SAS internal disk drives
|1|Dell PowerEdge M720|2x Intel(R) Xeon(R) CPU X5650 @ 2.67 GHz (6
core), 2 x Broadcom NetXtreme II BCM5709S Gb Ethernet, 2x  Emulex
Corporation OneConnect 10Gb NIC, 6 x DDR3 8192 MB @1333 MHZ DIMMs, 12x
146GB SAS internal disk drives
|====

[appendix]
== Required channels
Red Hat Enterprise Linux OpenStack Platform is available via the Content Delivery Network or Satellite Server.

.Required channels
[options="header,footer"]
|====
|Name|Description
|rhel-7-server-extras-rpms|Red Hat Enterprise Linux 7 Server - Extras
|rhel-7-server-openstack-7.0-director-rpms|Red Hat OpenStack 7.0 director for RHEL 7 (RPMs)
|rhel-7-server-openstack-7.0-rpms|Red Hat OpenStack 7.0 for RHEL 7 (RPMs)
|rhel-7-server-optional-rpms|Red Hat Enterprise Linux 7 Server - Optional (RPMs)
|rhel-7-server-rpms|Red Hat Enterprise Linux 7 Server (RPMs)
|====

NOTE: This reference architecture uses a local satellite server for
deployments and updates.

[appendix]
== Deploying undercloud with SSL

This appendix describes steps for deploying the undercloud with SSL
support.


. Generate a private key file.
----
[stack@rhos0 ~]$ openssl genrsa -out privkey.pem 2048
Generating RSA private key, 2048 bit long modulus
.....................................................................+++
.........+++
e is 65537 (0x10001)
----

. Create the distinguished identifier for the certificate.
NOTE: Replace this example with appropriate environment-specific answers.
----
[stack@rhos0 ~]$ openssl req -new -x509 -key privkey.pem -out
cacert.pem -days 365
You are about to be asked to enter information that will be
incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or
a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
\-----
Country Name (2 letter code) [XX]:US
State or Province Name (full name) []:Texas
Locality Name (eg, city) [Default City]:Austin
Organization Name (eg, company) [Default Company Ltd]:Red Hat
Organizational Unit Name (eg, section) []:Systems Engineering
Common Name (eg, your name or your server's hostname) []:192.0.2.2
Email Address []:jliberma@redhat.com
----

. Write the certificate and key to _undercloud.pem_.
----
[stack@rhos0 ~]$ cat cacert.pem privkey.pem > undercloud.pem
----

. Copy the combined SSL key to _/etc/pki/instal-cert/_.
----
[stack@rhos0 ~]$ sudo mkdir /etc/pki/instack-certs
[stack@rhos0 ~]$ sudo cp ~/undercloud.pem /etc/pki/instack-certs/.
----

. Set the SELinux context on the key certificate directory and files.
----
[stack@rhos0 ~]$ sudo semanage fcontext -a -t etc_t
"/etc/pki/instack-certs(/.*)?"
[stack@rhos0 ~]$ sudo restorecon -R /etc/pki/instack-certs
----

. Modify the undercloud.conf from the previous example to include:
.. An undercloud public VIP
.. An undercloud private VIP
.. The location for the undercloud service certificate.
----
[stack@rhos0 ~]$ head undercloud.conf 
[DEFAULT]

image_path = .
local_ip = 192.0.2.1/24
undercloud_public_vip = 192.0.2.2
undercloud_admin_vip = 192.0.2.3
undercloud_service_certificate = /etc/pki/instack-certs/undercloud.pem
local_interface = eno4
masquerade_network = 192.0.2.0/24
dhcp_start = 192.0.2.5
----

. Install the undercloud with SSL support.
----
[stack@rhos0 ~]$ openstack undercloud install
...
#############################################################################
instack-install-undercloud complete.

The file containing this installation's passwords is at
/home/stack/undercloud-passwords.conf.

There is also a stackrc file at /home/stack/stackrc.

These files are needed to interact with the OpenStack services, and
should be
secured.

#############################################################################
----
. Source _stackrc_ and verify the OpenStack services have separate
  internal and public endpoint URLs.
----
[stack@rhos0 ~]$ source ~stackrc
[stack@rhos0 ~]$ openstack endpoint show glance
    +--------------+----------------------------------+
    | Field        | Value                            |
    +--------------+----------------------------------+
    | adminurl     | http://192.0.2.1:9292/           |
    | enabled      | True                             |
    | id           | 6f715600451f433f98e38b72a5b70606 |
    | internalurl  | http://192.0.2.1:9292/           |
    | publicurl    | https://192.0.2.2:13292/         |
    | region       | regionOne                        |
    | service_id   | 8553ca00fa2c4aa98b1d60aa53df3f89 |
    | service_name | glance                           |
    | service_type | image                            |
    +--------------+----------------------------------+
----

[appendix]
== undercloud service list

neutron-dhcp-agent
neutron-openvswitch-agent
neutron-server
openstack-ceilometer-alarm-evaluator
openstack-ceilometer-alarm-notifier
openstack-ceilometer-api
openstack-ceilometer-central
openstack-ceilometer-collector
openstack-ceilometer-notification
openstack-glance-api
openstack-glance-registry
openstack-heat-api-cfn
openstack-heat-api-cloudwatch
openstack-heat-api
openstack-heat-engine
openstack-ironic-api
openstack-ironic-conductor
openstack-ironic-discoverd-dnsmasq
openstack-ironic-discoverd
openstack-keystone
openstack-nova-api
openstack-nova-compute
openstack-nova-conductor
openstack-nova-consoleauth
openstack-nova-scheduler
openstack-swift-account-auditor
openstack-swift-account-reaper
openstack-swift-account-replicator
openstack-swift-account
openstack-swift-container-auditor
openstack-swift-container-replicator
openstack-swift-container-updater
openstack-swift-container
openstack-swift-object-auditor
openstack-swift-object-replicator
openstack-swift-object-updater
openstack-swift-object
openstack-swift-proxy
openstack-tuskar-api


// vim: set syntax=asciidoc:
