[conclusion]
== Conclusion
{ospver} is Red Hat's 5th iteration of {ro}
based on the Kilo community OpenStack release. The reference architecture
introduces {ro} director -- Red Hat's integrated management tool set
-- and describes Red Hat's approach to OpenStack HA. It
also describes the steps performed by the Red Hat Systems Engineering
team to deploy a highly available {ro} 7 cluster running
a modern {eapver}  microservices application installed and configured via
nested `Heat` templates. Every step in the reference architecture was
tested with customer-available code on bare metal servers. It
complements existing documentation by providing a comprehensive
example of using {ro} director in a realistic
environment with its own hardware and network constraints.

The use case provides:

1. undercloud installation steps including post-installation
   configuration of the database and `Neutron` quotas.
2. overcloud installation steps including post-installation
   configuration of the Pacemaker resource constraints and fence
   devices.
3. A fully worked example of Ceph OSD and journal customization via Puppet Hiera
   data accompanied by post-installation configuration steps for
   increasing placement group settings for improved performance.
4. A fully worked example of network isolation configuration that
   describes a sensible method for collapsing multiple networks onto
   four physical interfaces using both tagged and native VLANs.
5. A detailed description of Red Hat's approach to highly available
   OpenStack including service placement and protection as implemented
   by {ro} director.
6. A fully worked example of deploying a multi-tiered {eapver}
   application using nested `Heat` templates.

EAP microservices applications can be delivered via Red Hat OpenShift
Enterprise using containers or another PaaS model. However, the use
case is still valid from a DevOps perspective for staging and
developing the application, and also for customers who are reluctant
to move to PaaS because they already have a substantial investment in
existing IaaS infrastructure. Also, although it is not covered in this
reference architecture, OpenStack can put additional muscle behind an
EAP 6 microservices application when it is coupled with `Heat` and
`Ceilometer` auto-scaling functionality. Auto-scaling the EAP 6
application behind a `Neutron` LBaaS has potential as an interesting
direction for future work.

<<<
