[chapter 5]
== Install the undercloud
This section lists the steps to install and configure {ospver} with
{ro} director in the Red Hat Systems Engineering lab.

=== Prepare the undercloud server

The following steps are to be performed within the undercloud server as the `root` user unless otherwise specified.

1. Install the operating system.
+
[subs=+quotes]
----
# *cat /etc/redhat-release*
Red Hat Enterprise Linux Server release 7.1 (Maipo)
----
+
2. Set the hostname using the `hostnamectl` command.
+
[subs=+quotes]
----
# *hostnamectl set-hostname rhos0.osplocal*
# *hostnamectl set-hostname --transient rhos0.osplocal*
# *export HOSTNAME=rhos0.osplocal*
# *hostname*
rhos0.osplocal
----
+
3. Register the system with `subscription-manager`.
+
[subs=+quotes]
----
# *subscription-manager register --org syseng --activationkey OSP7-undercloud*
The system has been registered with ID:
84e0fb33-24b0-4a1d-968e-e80352daa4f6
Installed Product Current Status:
Product Name: Red Hat Enterprise Linux Server
Status:       Subscribed
----
+
NOTE: In this example the system is registered to a satellite server
via an organization activation key. The
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/7/html/Director_Installation_and_Usage/sect-Registering_your_System.html[product documentation] includes
instructions for registering directly via
`subscription-manager`.
https://access.redhat.com/documentation/en-US/Red_Hat_Satellite/6.0/pdf/Provisioning_Guide/Red_Hat_Satellite-6.0-Provisioning_Guide-en-US.pdf[The
Red Hat Satellite 6.0 Provisioning Guide] includes instructions for
creating an organization activation key.
4. List active repositories.
+
[subs=+quotes]
----
# *yum repolist*
Loaded plugins: langpacks, product-id, rhnplugin, subscription-manager
This system is receiving updates from RHN Classic or Red Hat
Satellite.
repo id                                                        repo name status
rhel-7-server-extras-rpms/x86_64                               Red Hat Enterprise Linux 7 Server - Extras (RPMs) 89
rhel-7-server-openstack-7.0-rpms/7Server/x86_64                Red Hat OpenStack 7.0 for RHEL 7 (RPMs) 497
rhel-7-server-optional-rpms/7Server/x86_64                     Red Hat Enterprise Linux 7 Server - Optional (RPMs) 5,674
rhel-7-server-rpms/7Server/x86_64                              Red Hat Enterprise Linux 7 Server (RPMs) 7,392
rhel-x86_64-server-7                                           Red Hat Enterprise Linux Server (v. 7 for 64-bit x86_64) 7,424
repolist: 21,076
----
+
NOTE: Appendix D <<Appendix-required-channels>> lists the required channels.
+
5. Create the `stack` user
+
[subs=+quotes]
----
# *useradd stack*
# *echo 'stack:password' | chpasswd*
# *echo "stack ALL=(root) NOPASSWD:ALL" | tee -a /etc/sudoers.d/stack*
stack ALL=(root) NOPASSWD:ALL
# *chmod 0440 /etc/sudoers.d/stack*
# *id stack*
uid=1000(stack) gid=1000(stack) groups=1000(stack)
----

=== Deploy the Control Plane
1. Switch to the `stack` user account.
+
[subs=+quotes]
----
# *su - stack*
$ *id*
uid=1000(stack) gid=1000(stack) groups=1000(stack) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
----
+
2. Install the {ro} director plugin.
+
[subs=+quotes]
----
$ *sudo yum install -y -q python-rdomanager-oscplugin*
$ *sudo rpm -q python-rdomanager-oscplugin*
python-rdomanager-oscplugin-0.0.8-44.el7ost.noarch
----
+
3. Create the _undercloud.conf_. This file contains
  configuration data for the undercloud installation.
+
[source%autofit, ruby, numbered]
----
  [DEFAULT]

  image_path = .
  local_ip = 192.0.2.1/24
  local_interface = eno4
  masquerade_network = 192.0.2.0/24
  dhcp_start = 192.0.2.5
  dhcp_end = 192.0.2.24
  network_cidr = 192.0.2.0/24
  network_gateway = 192.0.2.1
  discovery_interface = br-ctlplane
  discovery_iprange = 192.0.2.100,192.0.2.120
  discovery_runbench = false
  undercloud_debug = true

  [auth]

  undercloud_db_password =
  undercloud_admin_token =
  undercloud_admin_password =
  undercloud_glance_password =
  undercloud_heat_encryption_key =
  undercloud_heat_password =
  undercloud_neutron_password =
  undercloud_nova_password =
  undercloud_ironic_password =
  undercloud_tuskar_password =
  undercloud_ceilometer_password =
  undercloud_ceilometer_metering_secret =
  undercloud_ceilometer_snmpd_user =
  undercloud_ceilometer_snmpd_password =
  undercloud_swift_password =
  undercloud_rabbit_cookie =
  undercloud_rabbit_password =
  undercloud_rabbit_username =
  undercloud_heat_stack_domain_admin_password =
  undercloud_swift_hash_suffix =
----
+
`eno4` is the provisioning network interface. Blank passwords are
auto-generated by the installer. Accept `br-ctlplane` as the default
discovery interface.
+
`discovery_runbench` is set to _false_. When enabled, the `Ironic`
instances are booted to a RAMdisk image that runs a series of
benchmark tests and reports outliers. This is beyond the scope of this
reference architecture.
+
NOTE: Installing with SSL support is beyond the scope of this
reference architecture. For details on how to use SSL support for the
undercloud see
https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux_OpenStack_Platform/7/html/Director_Installation_and_Usage/chap-Installing_the_Undercloud.html[the
product documentation] or Appendix E <<Appendix-undercloud-SSL>>.
+
4. Install the undercloud.
+
[subs=+quotes]
----
$ *openstack undercloud install | tee uc.out*

... [Output Abbreviated] ...
#############################################################################
instack-install-undercloud complete.

The file containing this installation's passwords is at
/home/stack/undercloud-passwords.conf.

There is also a stackrc file at /home/stack/stackrc.

These files are needed to interact with the OpenStack services, and should be secured.
#############################################################################
----
+
5. Source _stackrc_ to set environment variables for interacting with the undercloud.
+
[subs=+quotes]
----
$ *source stackrc*
$ *env | grep OS_*
OS_PASSWORD=7f1dbeead29fe7b1ca96fcf4bec20efb1717f6db
OS_AUTH_URL=http://192.0.2.1:5000/v2.0
OS_USERNAME=admin
OS_TENANT_NAME=admin
OS_NO_CACHE=True
----
+
6. Verify all services are active.
+
NOTE: This command output was truncated for brevity. Verify all
services are _active_. Appendix F <<Appendix-undercloud-servce-list>>
lists the OpenStack services running on the undercloud.
+
[subs=+quotes]
----
$ *openstack-service status*
neutron-dhcp-agent (pid 16458) is active
neutron-openvswitch-agent (pid 17750) is active
neutron-server (pid 16517) is active
openstack-ceilometer-alarm-evaluator (pid 16101) is active
openstack-ceilometer-alarm-notifier (pid 16033) is active
openstack-ceilometer-api (pid 16068) is active
openstack-ceilometer-central (pid 15998) is active
openstack-ceilometer-collector (pid 15965) is active
openstack-ceilometer-notification (pid 15932) is active
...
----
+
7. Increase the maximum database connections. This is recommended for
   production cluster deployments in
   https://access.redhat.com/articles/1432053[Performance Tuning the
   Backend Database for Red Hat Enterprise Linux OpenStack Platform].
+
[subs=+quotes]
----
$ **sudo sed -i 's/max_connections =.\*$/max_connections = 4096/' /etc/my.cnf.d/server.cnf**
----
+
8. Verify the connections have been increased.
+
[subs=+quotes]
----
$ *sudo grep max_connections /etc/my.cnf.d/server.cnf max_connections = 4096*
----
+
9. Increase the connection limit for the running databases and verify.
+
[subs=+quotes]
----
$ *sudo mysql -e "SET GLOBAL max_connections = 4096"*
$ *sudo mysql -e "SHOW GLOBAL VARIABLES LIKE 'max_connections'"*
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 4096  |
+-----------------+-------+
----
+
10. Increase or disable `Neutron` port quotas. In this example the port
   quota is disabled in order to accommodate all of the ports created
   for the overcloud servers and Pacemaker VIPs.
+
NOTE: A https://bugzilla.redhat.com/show_bug.cgi?id=1243121[bug]
tracking this issue has been filed to change the default `Neutron` port
quota to accommodate network isolation.
+
[subs=+quotes]
----
$ *neutron quota-update --port -1*
+---------------------+-------+
| Field               | Value |
+---------------------+-------+
| network             | 10    |
| port                | -1    |
| security_group      | 10    |
| security_group_rule | 100   |
| subnet              | 10    |
+---------------------+-------+
----

<<<
