CREATE DATABASE sales;
USE sales;
CREATE USER 'sales'@'%' IDENTIFIED BY 'password';
GRANT USAGE ON *.* TO 'sales'@'%' IDENTIFIED BY 'password';
CREATE TABLE Customer (ID BIGINT NOT NULL AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL, ADDRESS varchar(255), EMAIL varchar(255) NOT NULL, PASSWORD varchar(255), TELEPHONE varchar(255), USERNAME varchar(255) NOT NULL UNIQUE, PRIMARY KEY (ID)) AUTO_INCREMENT = 100001;
CREATE TABLE Orders (ID BIGINT NOT NULL AUTO_INCREMENT, STATUS INTEGER, TRANSACTIONDATE DATETIME, TRANSACTIONNUMBER BIGINT, CUSTOMER_ID BIGINT NOT NULL, PRIMARY KEY (ID)) AUTO_INCREMENT = 100001;
ALTER TABLE Orders ADD INDEX FK_ORDER_CUSTOMER (CUSTOMER_ID), add constraint FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES Customer (ID);
CREATE TABLE OrderItem (ID BIGINT NOT NULL AUTO_INCREMENT, SKU BIGINT NOT NULL, QUANTITY INTEGER NOT NULL, ORDER_ID BIGINT NOT NULL, PRIMARY KEY (ID)) AUTO_INCREMENT = 1000001;
ALTER TABLE OrderItem ADD INDEX FK_ORDERITEM_ORDER (ORDER_ID), add constraint FK_ORDERITEM_ORDER FOREIGN KEY (ORDER_ID) REFERENCES Orders (ID);

GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP on sales.* to 'sales'@'%';

